### PR TITLE
Sentence and word revisions (lpic2.200.1.md)

### PR DESCRIPTION
**Pull request by JustALawnGnome7**
Removed hanging text (generally duplicates) from previous edits, and corrected errors in spelling, grammar, and sentence structure. Considerable changes were made to the language in the "Estimate throughput and identify bottlenecks in a system including networking" section.

### CODE REVIEW

**Comment by JustALawnGnome7** [comment]
Okay, so here's where my knowledge of the GitHub commit/pull request process is a little shaky. I don't know what just happened to cause a new event in this pull request to appear, but it was unintentional:

Merge branch 'lpic2book:main' into main

**Comment by CoMPaTech** [comment]
I guess you wanted to update your local clone?
Just mostly history guessing here and sort of advising what to do for what you aimed for

So you 'forked' the repo using the button, then did something like
```
git clone git@github.com:yourrepo/lpic2book.git # or likewise
git branch -m yourbranch
# insert edit commands here
git add -A ; git commit -m 'My awesome commit' ; git push origin yourbranch
# there git inserted a 'he, click this button to create a pr
```

To have `git` know they are linked you set another origin (`git remote -v` only shows `origin` now). Do note that you can either `https` or `ssh` git clone your repo, but you can only `https` the remote (since in general / most likely you are not a contributor for an upstream repo)

```
git remote add upstream https://github.com/lpic2book/src.git
# tell git that something you call 'upstream' is at another origin, you could have called it anything really
git remote -v 
# see?
# now you can fetch the upstream
git fetch upstream # or git fetch upstream branchnamehere
git rebase upstream # or git rebase upstream/branchenamehere
# git will then rewind your changes, forward to the upstream version, then reapply your changes
# if anything is wrong it will bother you to edit your files (look for >>> and <<<) and git add them again then
git rebase --continue
# if you can't make it work you can always 
git rebase --abort
```

Thats just a very short gist about it, what I would highly recommend is just have a go at the first chapters of https://lab.github.com its starts out very basic, but fetching/branching and everything is in it in a learning and playfull environment.

**Comment by EnemyTurret** [comment]
@JustALawnGnome7 This pull request requests to merge your main branch to this repo's main branch, so when you merged the latest changes upstream to your main branch it made a commit to the branch this pull request is trying to merge and that's why you can see that commit here. I'm not a GitHub expert myself, but it seems to have [pretty good documentation](https://docs.github.com/en), here's a page explaining [the various forms of communication on GitHub](https://docs.github.com/en/get-started/quickstart/communicating-on-github)

**Comment by JustALawnGnome7** [comment]
You folks are awesome, thanks!

**Comment by JustALawnGnome7** [comment]
From everything I've read (from you folks, from the links that you've included in your comments, and from other sources I've encountered over the last week), it seems that my real problem stems from the fact that I didn't create a branch separate from "main" when I began making changes (and submitting pull requests). I will be sure to better manage this in the future. I will also review 

As for what happens next, what more must be done before this pull request can be merged into "lpic2book/src"? I can see that the two usual contributors have already approved the changes in the pull request. Will my changes just be merged at a later date, or is there something more that you folks need from me?

**Comment by CoMPaTech** [comment]
See https://github.com/lpic2book/src/pull/10#issuecomment-954712843 just above - if thats resolved and/or fine we can just push the 'merge' button (it's probably not visible for you, but for us it is)

**Comment by CoMPaTech** [comment]
And you are right about the branching, I just spotted that you are in fact having main :)

**Comment by JustALawnGnome7** [comment]
> See [#10 (comment)](https://github.com/lpic2book/src/pull/10#issuecomment-954712843) just above - if thats resolved and/or fine we can just push the 'merge' button (it's probably not visible for you, but for us it is)

Yes, it's fine. We should be able to just merge.

**Comment by CoMPaTech** [comment]
Merged :) Tnx for the contribution!

**Pull request merged**
