### PR TITLE
Update lpic2.201.1.md

### PR DESCRIPTION
**Pull request by dmitrysomov**
fix several artifacts that apparently appeared during conversion to html (NDASH to '-', remove '/', add spaces)

### CODE REVIEW

**Review by stappersg — APPROVED** [review]
Looks good to me.

**Comment by CoMPaTech** [comment]
@stappersg should I merge or add you to the team so you can merge?

**Comment by stappersg** [comment]
> @stappersg should I merge or add you to the team so you can merge?

The silence between the opening of the issue and my _LGTM_ indicates that the team could use additional members.  So yes, add me to the team.

**Comment by CoMPaTech** [comment]
I would love a bigger community, you should have the invite

**Comment by stappersg** [comment]
* Got _invite_
* _invite_ accepted
* Merged this merge request

**Comment by stappersg** [comment]
> I would love a bigger community

Yeah, _plus one_ for sharing workload and other fun.

**Pull request merged**
